name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: dps
      run: brew install cmake
    - name: mkdir
      run: mkdir build && cd build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: make -j 2
    - name: ls
      run: ls -l

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: exe
        path: build
