name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake .
    - name: build
      run: cmake --build . -j8 --config Release
    - name: ls
      run: ls -l

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: exe
        path: offset3d
